{% set name = "fluentd" %}
{% set version = "1.10.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a7ba010b64d43af82738e058b76a45f7918aa7409b59d6b1738a34d0c10a7096

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
      && gem unpack {{ name }}-{{ version }}.gem  # [rb26]
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-cool.io >=1.4.5,<2.0.0
    - rb-dig_rb >=1.0.0,<1.1
    - rb-http_parser.rb >=0.5.1,<0.7.0
    - rb-msgpack >=1.2.0,<2.0.0
    - rb-serverengine >=2.0.4,<3.0.0
    - rb-sigdump >=0.2.2,<1.0.0
    - rb-strptime >=0.2.2,<0.3
    - rb-tzinfo >=2.0,<3
    - rb-tzinfo-data >=1.0,<2
    - rb-yajl-ruby >=1.0,<2

test:
  commands:
    - {{ name }} --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: |
    Fluentd is an open source data collector designed to scale and simplify
    log management. It can collect, process and ship many kinds of data
    in near real-time.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/fluent/fluentd

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - conda-forge/ruby
