{% set name = "fluentd" %}
{% set version = "1.14.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a34a4f10e3237de5071aec281e35706db5b0b4ca6eac1ca415a1ba66b13fc469 

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5
  run:
    - ruby >=2.5
    - rb-bundler >=0
    - rb-cool.io >=1.4.5,<2.0.0
    - rb-http_parser.rb >=0.5.1,<0.7.0
    - rb-msgpack >=1.3.1,<2.0.0
    - rb-serverengine >=2.2.2,<3.0.0
    - rb-sigdump >=0.2.2
    - rb-strptime >=0.2.2,<1.0.0
    - rb-tzinfo >=1.0,<3.0
    - rb-tzinfo-data >=1.0
  #  - rb-webrick >=1.4.2,<1.8.0 
    - rb-yajl-ruby >=1.0

test:
  commands:
    - {{ name }} --help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: APACHE
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: |
    Fluentd is an open source data collector designed to scale and simplify
    log management. It can collect, process and ship many kinds of data
    in near real-time.
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/fluent/fluentd

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/ruby
