travis:
  secure:
    BINSTAR_TOKEN: dApEPXgP8kpkKIbuCeRg003NtC1Ns+Pl5lOH5z1jmTa2BuoB+xCiafiuoAfkMac18zvK7PawZXWueGh+gQ2D4nXg+FAx3kXRdO6lF1s2Y3tlpRxE793/ax9oWnukr5xEXu8ErEYdj299FKZ3BZRRUI74dtpGUE14zpb841GPg88ssgvQfrmyq2cn0ipHifZQeC1lPAt+nV2XjMQnIBEPVzZzvZDMzgUjfR5q7KJNrXeMKaOtLdMahLxntEG47WsFNYsew0FP7uHyeCKEu6dNbwfGAnHBtihEDfyUebeGB5w7DNReNtDWluoR6IR8EmoqnJpgEATDrRibJn7shds2lSBO8R7yaJHUAWbIGS1jHGkxqNYp6IrAP1EKy7TnnYIV68UXF84+lr+fLNF6jPjpnEDecgs/Bkix8BZ42pqJZBEL6WwMoHF41ZAsFX4sgXIyWfcmbRvh9MSciTVDCNW4+xM1JvPdWsnEZO7KF4hiu+zcU7WanoEh4cLZwLQzzjA760oRz0CsqCvaycdlsTcLFa7B0BpE9lAVk3/f2O44XAe4fYnJFNrK9hLh+2lVhylmZFSLJ1ffRPTD0/qiDsSARuF6h8s426fbNZ0mLzKFTiEzrvx+xAr0gTywVjZJcS9Ol7wlJ2dHa1R86EUVUFRg+AhaFIFImyE8UMsArLYkqyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
